isin_code: "LU1301026206"
vl-eur: "194,6€"
aum: "428,1 M€"

person_1_name: "Giulia CULOT"
person_1_job: "Gérante"

person_2_name: "Luca FASAN"
person_2_job: "Gérant"

person_3_name: "Claire MOUCHOTTE"
person_3_job: "Analyste ISR"
