text:
  isin_code: "LU1301026206"
  vl-eur: "194,6€"
  aum: "428,1"
  
  person_1_name: "Giulia CULOT"
  person_1_job: "Gérante"
  
  person_2_name: "Luca FASAN"
  person_2_job: "Gérant"
  
  person_3_name: "Claire MOUCHOTTE"
  person_3_job: "Analyste ISR"

  rounding: 2

format:
  font: "Arial"       # Police de caractère
  size: 12           # Taille de la police
  bold: true         # Texte en gras

image:
  path: "Sycomore_logo.png"
  size: [2, 2]       # Taille de l'image (largeur, hauteur) en pouces

table:
  headers:
    - "Nom"
    - "Poste"
  data:
    - ["Giulia CULOT", "Gérante"]
    - ["Luca FASAN", "Gérant"]
    - ["Claire MOUCHOTTE", "Analyste ISR"]


array_from_excel:
  path: